### ISSUE TITLE
New Yorker puzzles not downloading

### ISSUE THREAD

**Issue by aanker** [thisisparker/xword-dl#60]
Starting on Wednesday, I'm no longer able to download New Yorker puzzles. All of the other sites I pull from (WSJ, Atlantic, LAT) work fine, just New York and the error is consistent every time. Am I the only one having a problem?

Error message:
```
Traceback (most recent call last):
  File "/Users/aa/opt/anaconda3/bin/xword-dl", line 8, in <module>
    sys.exit(main())
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/xword_dl.py", line 1139, in main
    puzzle, filename = by_url(args.source,
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/xword_dl.py", line 102, in by_url
    puzzle = dl.download(puzzle_url)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/xword_dl.py", line 265, in download
    solver_url = self.find_solver(url)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/xword_dl.py", line 616, in find_solver
    pubdate_dt = dateparser.parse(pubdate)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/__init__.py", line 54, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/date.py", line 421, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/date.py", line 178, in parse
    return instance._parse()
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/languages/locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/languages/locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/dateparser/languages/locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/regex/regex.py", line 702, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "/Users/aa/opt/anaconda3/lib/python3.9/site-packages/regex/_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
```

I tried uninstalling and reinstalling, I uninstalled the regex package thinking maybe I had a weird version. I created a new venv, nothing seems to fix it and like I said, all the other puzzles seem to work. I tried using the normal behavior (`xword-dl tny`) and tried installing by URL, the problem happens regardless.

This does sync up with some updating of my Python environment that I did so I was pretty sure this was my problem but the fact that it only happens to New Yorker puzzles made me wonder. Apologies in advance if it does end up being my problem, it's happened many times...

**Comment by thisisparker** [comment]
Should now be fixed on new installs!
